### ISSUE TITLE
Problem with ArchiveRemoteFolder

### ISSUE THREAD

**Issue by PaddySe** [ggarbuglia/TfsExtensions#4]
Hi,

I just found the ArchiveRemoteFolder extension - awesome!! :)

However, when trying to use it, I get the following error message (I'm running TFS 2017 On-Premises, and the remote server is a Windows Server 2012 R2):

> ##[error]System.Management.Automation.RemoteException: 'C:\Program' is not recognized as an internal or external command, operable program or batch file.

**Comment by ggarbuglia** [comment]
PaddySe can you please give me some more info? At first sight I think is the space in 'Program Files' but we tested a lot using paths with spaces and no problems were reported. Are you using a variable to inject the path as a value? Keep me posted. Thanks!

**Comment by PaddySe** [comment]
That's the strange part. I imported the task from the market place, added it to a simple release, configuring remote machine, admin login and password, source and target paths, 7z filename, date stamp format and retension. It's a very simple release definition, no variables defined.

**Comment by PaddySe** [comment]
I just tested it "manually" in Powershell, and I can get it to work if I on line 73 change

cmd /c "`"$env:ProgramFiles\7-Zip\7z.exe`" a -t7z `"$targetPath$fileName`" `"$sourcePath*.*`" -r $($exclusionlist.TrimEnd())"

to

7z a -t7z "$targetPath$fileName" "$sourcePath*.*" -r $($exclusionlist.TrimEnd())

**Comment by ggarbuglia** [comment]
WTF? So you removed the environment variable and it works? Mmm did you install the 64bits version of 7z? Totally strange!!!

**Comment by PaddySe** [comment]
Well, yes and no. I removed the starting of a new command shell (the cmd /c part), and instead ran the 7z executabe inside powershell. Trying to double-escape quotes has been... troublesome for me in the past. :)

I'm not sure why you start a new command shell to run the 7z program in?

**Comment by PaddySe** [comment]
This was a long time ago, I can't really recall what I ended up doing. I'm closing this :)
