### ISSUE TITLE
RunSqlServerScripts - When the directory to copy files from is empty, an error is received

### ISSUE THREAD

**Issue by cameronpresley** [ggarbuglia/TfsExtensions#6]
When running the task, if the selected folder that contains scripts is empty, the step fails with the following logs: 

- Creating Script Blocks.
- Creeating Secured Credentials.
- Opening Powershell remote session on localhost.
- Setting up remote session.
- ##[debug]Processed: ##vso[task.setprogress value=-1;] 
- ##[debug]Processed: ##vso[task.setprogress value=-1;] 
- Copying scripts to remote session.
- ##[error]Microsoft.PowerShell.Commands.WriteErrorException: A parameter cannot be found that matches parameter name 'ToSession'.
- ##[debug]Processed: ##vso[task.logissue type=error;]Microsoft.PowerShell.Commands.WriteErrorException: A parameter cannot be found that matches parameter name 'ToSession'.
- Closing Powershell remote session on localhost.

I would expect that if there are no scripts in the directory, then the step would succeed.

This is current behavior with the latest version of the task and the current version of Visual Studio Team Services.

Thoughts?
Cameron

**Comment by ggarbuglia** [comment]
Hi Cameron!
Sorry to hear that you have this problem.
The task was created to copy scripts and execute them. That's the normal behavior and the goal for success state.
If no scripts are present the hole Task cannot meet the goal. 
So I recommend you to make the changes you like to the Powershell script in order to meet your specific needs. If you need help I'll be glad to assist you. 

Have a nice day!

**Comment by cameronpresley** [comment]
Just to make sure I understand, you're saying that if the current deployment didn't have any scripts to execute, then that's an acceptable reason for the deployment to fail?

**Comment by ggarbuglia** [comment]
Yes. But for us, it never fails. Why? Because we always provide the necessary input (the scripts)  to be consumed and processed. In fact, the whole intention is to do something with the scripts. Not with air. Remember that the Task name is RunSqlServerScripts.

**Comment by cameronpresley** [comment]
So what would you do if there were no scripts to run? That's where I'm confused. Unless you're saying that for every deployment, there's always at least one script to be deployed.

Thanks for the quick responses, I definitely appreciate it!

**Comment by ggarbuglia** [comment]
OK. First let's talk about how we have deployments in our Release system. 

SQL Server changes are not tied up to continue delivery of other pieces of software. So we schedule schema or data updates separately and on demand. Make sense?

So, when we queue a SQL Server change to be deployed, we ensure that the necessary assets or scripts are present in the spected folder, related to some Build. We deploy only that Change Request before some other Build with compiled code or assets. 

Hope I make myself clear.

**Comment by cameronpresley** [comment]
Ah, given that use case, I can see why the task was designed that way. 

The use case we have is that we deploy all changes for a release at the same time. Given that we do frequent, short releases, there are times where there are no  scripts to be deployed and that's how we found this error.

Thank you for explaining and with your blessing, I'll make the tweaks to the script to make it work for our use case.

**Comment by ggarbuglia** [comment]
Go for it. If you need any help I'm here.

**Comment by cameronpresley** [comment]
Thanks!
